### ISSUE TITLE
Set up Travis.CI

### ISSUE THREAD

**Issue by scottmconway** [scottmconway/csec380_project#12]

**Comment by becksteadn** [comment]
Since you're the owner of the GitHub repo I think you'll need to sign up and connect it to Travis.

**Comment by scottmconway** [comment]
I've done so. It should work automatically on the next push to the repo.

**Comment by becksteadn** [comment]
I made a directory for tests. `helloworld` builds a NGINX webserver and runs a Python script with Selenium that renders it in Firefox.
